name: MCToon
main: yuu528\MCToon\Main
version: 1.0
description: Splatoonの再現プラグイン
api: 1.10.0
load: POSTWORLD
author: yuu528

commands:
 mcto:
  description: MCToonのOPコマンドです
  usage: /mcto <args>
  permission: mctoon.cmd.op

 reg:
  description: サーバーに登録するためのコマンドです
  usage: /reg <パスワード>
  permission: mctoon.cmd.guest

 login:
  description: サーバーにログインするためのコマンドです
  usage: /login <パスワード>
  permission: mctoon.cmd.guest

permissions:
 mctoon.cmd.op:
  default: op

 mctoon.cmd.guest:
  default: true